apiVersion: v1
kind: Service
metadata:
  name: pg-db-service
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: pg-db-service
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: 5432
  selector:
    app.kubernetes.io/name: pg-db
