apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-db
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pg-db
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app.kubernetes.io/name: pg-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pg-db-config
            - secretRef:
                name: pg-db-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-db
      volumes:
      {{ if  .Values.db.pvc.enabled }}
        - name: pg-db
          persistentVolumeClaim:
            claimName: pg-db-pv-claim
      {{ else }}
        - name: pg-db
          emptyDir: {}
      {{ end }}
